<?php

namespace AppBundle\Repository;

/**
 * NewPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewPostRepository extends \Doctrine\ORM\EntityRepository
{
}
